CC=gcc
CFLAGS=-Wall -std=c99 -pedantic -g
NAME=LinkedListAPI

cppcheck:
	cppcheck --enable=all --language=c --std=c99 --inconclusive --suppress=missingInclude src/*.c -i ./include

$(NAME): $(NAME).o
	$(CC) -o $(NAME) $(NAME).o
$(NAME).o: $(NAME).c
	$(CC) $(CFLAGS) -c $(NAME).c
clean:
	rm $(NAME) $(NAME).o